import './style.css';
import { Battle } from './game/battle';
import { abilities, nightNames } from './game/data';
import { equipItem, itemByName, slots } from './game/equipment';
import { canPromote, jobTree, promote } from './game/jobs';
import { applyVictory, learn } from './game/progression';
import { loadGame, newGame, saveGame } from './game/save';
import { audio } from './core/AudioManager';
import { tutorialSteps } from './ui/tutorial';
import type { Hero, SaveGame, Station } from './game/types';

const app=document.querySelector<HTMLDivElement>('#app')!;
let game:SaveGame|null=null,battle:Battle|null=null,raf=0,last=0,renderAt=0,speed=1,selected='isabel',selectedBattle='',repairCharge=1,flareCharge=1,tutorialIndex=0;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(label:string,action:string,disabled=false)=>`<button data-action="${action}" ${disabled?'disabled':''}>${label}</button>`;
function closeTutorial(){document.querySelector('#tutorial-overlay')?.remove();document.querySelectorAll('.tutorial-focus').forEach(x=>x.classList.remove('tutorial-focus'));}
function showTutorial(index=0){closeTutorial();tutorialIndex=Math.max(0,Math.min(tutorialSteps.length-1,index));const step=tutorialSteps[tutorialIndex],target=step.target?document.querySelector(step.target):null;target?.classList.add('tutorial-focus');const overlay=document.createElement('div');overlay.id='tutorial-overlay';overlay.className='tutorial-overlay';overlay.innerHTML=`<div class="tutorial-backdrop" data-action="tutorial-close"></div><section class="tutorial-window" role="dialog" aria-modal="true" aria-label="How to Play"><div class="tutorial-progress">HOW TO PLAY · ${tutorialIndex+1}/${tutorialSteps.length}</div><h2>${step.title}</h2><p>${step.body}</p><aside>${step.tip}</aside><div class="tutorial-actions">${button('BACK','tutorial-back',tutorialIndex===0)}${button(tutorialIndex===tutorialSteps.length-1?'FINISH':'NEXT','tutorial-next')}</div><button class="tutorial-x" data-action="tutorial-close" aria-label="Close tutorial">×</button></section>`;document.body.append(overlay);}
function title(){const can=!!loadGame();app.innerHTML=`<section class="title-screen"><div class="moon"></div><div class="fortress"><span></span><span></span><span></span></div><div class="title-card"><p class="eyebrow">Gravenhold stands</p><h1>THE LAST WATCH</h1><p class="subtitle">Persistent heroes · Tower defense · Fortress restoration</p>${button('CONTINUE','continue',!can)}${button('NEW GAME','new')}<p class="status">The world may be dying. This place is still worth defending.</p></div><button class="help-fab" data-action="tutorial" aria-label="How to Play">?</button></section>`;}
function shell(content:string,active='War Room'){app.innerHTML=`<div class="game-shell ${active?'':'battle-mode'}"><header><div><small>GRAVENHOLD · CASTLE LV.${game!.castleLevel}</small><strong>DAY ${game!.day}</strong></div><div>◈ ${game!.gold} &nbsp; Integrity ${game!.integrity}%</div></header><nav>${['War Room','Barracks','Armory','Training','Jobs','Infirmary','Bestiary','Chronicle','Settings'].map(x=>button(x,`screen:${x}`,x===active)).join('')}</nav><main>${content}</main><footer>${button('Save 1','save:slot1')} ${button('Save 2','save:slot2')} ${button('Save 3','save:slot3')} ${button('Title','title')}</footer><button class="help-fab" data-action="tutorial" aria-label="How to Play">?</button></div>`;}
function war(){const stations:Station[]=['Gate','Wall','Archer Tower','Mage Post','Reserve'];shell(`<section class="screen"><div class="screen-title"><div><p class="eyebrow">War Room</p><h2>Night ${game!.night}: ${nightNames[Math.min(9,game!.night-1)]??'Beyond the First Watch'}</h2></div><div class="forecast">Forecast: ${game!.night===8?'Fog obscures the enemy.':'Undead approaching the north road.'}</div></div><div class="war-grid"><div class="map-card"><div class="route"><span>CURSED ROAD</span><i></i><i></i><i></i><b>KEEP</b></div><h3>Fortress defenses</h3>${game!.defenses.map(d=>`<div class="list-row"><span>${d.kind}</span><small>DMG ${d.damage} · RNG ${d.range}</small></div>`).join('')}<div class="builds">${button('Build Ballista · 80g','build:Ballista',game!.gold<80||game!.defenses.some(d=>d.kind==='Ballista'))}${button('Build Holy Ward · 70g','build:Holy Ward',game!.gold<70||game!.defenses.some(d=>d.kind==='Holy Ward'))}</div></div><div class="panel"><h3>Hero stations</h3>${game!.heroes.map(h=>`<label class="assign"><span><b>${h.name}</b><small>${h.job} · Lv.${h.level}</small></span><select data-hero="${h.id}">${stations.map(s=>`<option ${h.station===s?'selected':''}>${s}</option>`).join('')}</select></label>`).join('')}</div></div><div class="begin">${button(`BEGIN NIGHT ${game!.night}`,'begin')}</div></section>`,'War Room');}
function barracks(){shell(`<section class="screen"><div class="screen-title"><div><p class="eyebrow">Barracks</p><h2>The Seven Who Remain</h2></div></div><div class="roster">${game!.heroes.map(h=>`<button class="hero-card ${selected===h.id?'selected':''}" data-action="hero:${h.id}"><span class="portrait sprite hero-${h.id}"></span><b>${h.name}</b><small>Lv.${h.level} ${h.job}${h.injury?' · INJURED':''}</small><meter min="0" max="${h.level*100}" value="${h.xp}"></meter><small>XP ${h.xp}/${h.level*100} · JP ${h.jp}</small></button>`).join('')}</div>${heroSheet(game!.heroes.find(h=>h.id===selected)!)}</section>`,'Barracks');}
function heroSheet(h:Hero){return `<article class="sheet"><div><p class="eyebrow">Character sheet</p><h2>${h.name}</h2><p>${h.job} assigned to ${h.station}</p>${h.injury?`<p class="injury">${h.injury.name} · ${h.injury.recoveryDays} day(s)</p>`:''}</div><div class="stats"><span>HP <b>${h.maxHp}</b></span><span>ATK <b>${h.attack}</b></span><span>ARM <b>${h.armor}</b></span><span>RNG <b>${h.range}</b></span></div><div><h3>Equipment</h3>${slots.map(s=>`<p><small>${s.toUpperCase()}</small>${h.equipment[s]?itemByName(game!.inventory.find(n=>itemByName(n)?.id===h.equipment[s])||'')?.name||h.equipment[s]:'Empty'}</p>`).join('')}<h3>Skills</h3><p>${h.learned.join(' · ')||'No learned skills'}</p></div><div><h3>Relationships</h3>${h.relationships.map(r=>{const other=game!.heroes.find(x=>x.id===r.heroId);return `<p>${other?.name} · ${r.bond||r.affinity+' affinity'}</p>`}).join('')||'<p>No bonds yet.</p>'}<h3>History</h3>${h.history.slice(-4).map(x=>`<p class="history">${esc(x)}</p>`).join('')}</div></article>`;}
function training(){shell(`<section class="screen"><div class="screen-title"><div><p class="eyebrow">Training Hall</p><h2>Job Disciplines</h2></div></div><div class="skill-grid">${game!.heroes.map(h=>{const family=(h.masteredJobs[0]||h.job) as keyof typeof abilities,a=abilities[family]?.[0];return a?`<article><h3>${h.name}</h3><p>${h.job} · ${h.jp} JP</p><b>${a.name} · ${a.cost} JP</b><p>${a.description}</p>${button(h.learned.includes(a.name)?'LEARNED':'LEARN',`learn:${h.id}:${a.name}`,h.learned.includes(a.name)||h.jp<a.cost)}</article>`:''}).join('')}</div></section>`,'Training');}
function armory(){shell(`<section class="screen"><div class="screen-title"><div><p class="eyebrow">Armory</p><h2>Arms of Gravenhold</h2></div></div><div class="inventory">${game!.inventory.map(x=>{const item=itemByName(x);return `<article><span class="item-icon">✦</span><div><b>${esc(x)}</b><small>${item?`${item.rarity} ${item.slot} · ${item.effect||[item.attack&&`ATK +${item.attack}`,item.armor&&`ARM +${item.armor}`,item.range&&`RNG +${item.range}`].filter(Boolean).join(' · ')}`:'Crafting material'}</small></div>${item?`<select data-equip="${item.id}">${game!.heroes.map(h=>`<option value="${h.id}">${h.name}</option>`).join('')}</select>${button('Equip','equip:'+item.id)}`:''}</article>`}).join('')}</div></section>`,'Armory');}
function jobs(){shell(`<section class="screen"><div class="screen-title"><div><p class="eyebrow">Job Hall</p><h2>Paths of Service</h2></div></div><div class="job-tree">${game!.heroes.map(h=>`<article><span class="portrait sprite hero-${h.id}"></span><h3>${h.name} · ${h.job}</h3>${jobTree.filter(n=>n.from===h.job).map(n=>`<div class="job-node"><b>${n.name}</b><small>Lv.${n.level} · ${n.cost} JP</small><p>${n.description}</p>${button('PROMOTE',`promote:${h.id}:${n.name}`,!canPromote(h,n))}</div>`).join('')||'<p>Advanced discipline active.</p>'}</article>`).join('')}</div></section>`,'Jobs');}
function infirmary(){const hurt=game!.heroes.filter(h=>h.injury);shell(`<section class="screen"><div class="screen-title"><div><p class="eyebrow">Infirmary</p><h2>The Wounded</h2></div></div>${hurt.length?`<div class="skill-grid">${hurt.map(h=>`<article><span class="portrait sprite hero-${h.id}"></span><h3>${h.name}</h3><b>${h.injury!.name}</b><p>${h.injury!.penalty}</p><small>${h.injury!.recoveryDays} day(s) remaining</small></article>`).join('')}</div>`:'<div class="empty-state">No one lies wounded. The Chapel bells are quiet.</div>'}</section>`,'Infirmary');}
function settings(){shell(`<section class="screen"><div class="screen-title"><div><p class="eyebrow">Settings</p><h2>Command Preferences</h2></div></div><div class="settings"><label>Master Volume <input data-setting="master" type="range" min="0" max="1" step=".1" value="${game!.settings.master}"></label><label>Music <input data-setting="music" type="range" min="0" max="1" step=".1" value="${game!.settings.music}"></label><label>SFX <input data-setting="sfx" type="range" min="0" max="1" step=".1" value="${game!.settings.sfx}"></label><label><input data-setting="reducedMotion" type="checkbox" ${game!.settings.reducedMotion?'checked':''}> Reduced Motion</label><label><input data-setting="autoPause" type="checkbox" ${game!.settings.autoPause?'checked':''}> Auto-pause when a hero falls</label></div></section>`,'Settings');}
const stationX:Record<string,number>={Gate:88,Wall:64,'Archer Tower':58,'Mage Post':61,Reserve:84};
function heroBattleHtml(h:Hero,i:number){const x=Math.min(90,stationX[h.station]+((i%3)-1)*2),acting=!!battle&&h.nextAttack-battle.time>h.cooldown-.2;return `<button class="unit hero battle-sprite hero-${h.id} ${h.downed?'downed':''} ${acting?'attacking':''} ${acting&&(h.job==='Mage'||h.job==='Cleric')?'casting':''} ${selectedBattle===h.id?'selected-unit':''}" style="left:${x}%" title="${h.name}" data-action="inspect:hero:${h.id}"><em class="unit-hp" style="--hp:${Math.max(0,h.hp/h.maxHp*100)}%"></em><span>${h.name.split(' ')[0]}</span></button>`;}
function enemyTraits(kind:string,flying?:boolean){return [flying?'FLYING':'',kind.includes('Knight')?'ARMORED':'',kind.includes('Shade')||kind.includes('Priest')?'MAGICAL':'',kind.includes('Captain')?'ELITE':'',kind.includes('Warden')?'BOSS':''].filter(Boolean);}
function bestiary(){const kinds=['Grave Wretch','Briar Hound','Moon Bat','Rust Knight','Hollow Shade','Grave Priest','Grave Captain','The Bone Warden'];shell(`<section class="screen"><div class="screen-title"><div><p class="eyebrow">Library</p><h2>Bestiary</h2></div></div><div class="bestiary">${kinds.map(k=>`<article><span class="sigil">${game!.bestiary[k]?'☠':'?'}</span><div><b>${game!.bestiary[k]?k:'UNKNOWN'}</b><small>${game!.bestiary[k]>=3?'MASTERED':game!.bestiary[k]?'OBSERVED':'No research'}</small></div></article>`).join('')}</div></section>`,'Bestiary');}
function chronicle(){shell(`<section class="screen"><div class="screen-title"><div><p class="eyebrow">Commander’s Chronicle</p><h2>Gravenhold Remembers</h2></div></div><div class="chronicle">${game!.history.slice().reverse().map(x=>`<p>${esc(x)}</p>`).join('')}</div></section>`,'Chronicle');}
function night(){shell(`<section class="battle"><div class="battle-top"><div><b>NIGHT ${game!.night}</b><small>${nightNames[Math.min(9,game!.night-1)]}</small></div><div>WAVE <b id="wave">1</b></div><div>INTEGRITY <b id="integrity">100%</b></div><div>THREATS <b id="threats">0</b></div></div><div class="battlefield"><div class="sky"><div class="battle-moon"></div></div><div class="keep" aria-label="Gravenhold Keep"><span>GRAVENHOLD</span></div><div class="station-platforms"><i style="left:58%" data-label="ARCHER"></i><i style="left:64%" data-label="WALL"></i><i style="left:84%" data-label="RESERVE"></i><i style="left:89%" data-label="GATE"></i></div><div class="stations"></div><div id="entities"></div><div id="combat-effects"></div><div id="battle-alerts" aria-live="assertive"></div><aside id="battle-inspector"><b>TACTICAL INSPECTION</b><span>Tap a hero or enemy for combat details.</span></aside><div class="road"></div></div><div class="night-controls">${button('RALLY','rally')}${button('EMERGENCY REPAIR','repair')}${button('HOLY FLARE','flare')}<span></span>${button('Ⅱ PAUSE','speed:0')}${button('1×','speed:1')}${button('2×','speed:2')}</div></section>`,'');battle=new Battle(game!.night,game!.heroes,game!.defenses,game!.night*991);selectedBattle='';last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);}
function loop(now:number){
  if(!battle)return;
  const dt=Math.min(.05,(now-last)/1000)*speed;last=now;if(dt)battle.step(dt);
  if(now-renderAt>140){
    renderAt=now;
    const stations=document.querySelector('.stations');if(stations)stations.innerHTML=battle.heroes.filter(h=>!h.injury||h.downed).map(heroBattleHtml).join('');
    const e=document.querySelector('#entities');if(e)e.innerHTML=battle.enemies.map((x,i)=>{const traits=enemyTraits(x.kind,x.flying),acting=x.nextAttack-battle!.time>x.attackRate-.2;return `<button class="unit enemy battle-sprite enemy-${x.kind.toLowerCase().replaceAll(' ','-')} ${x.flying?'flying':''} ${acting?'attacking':''} ${traits.map(t=>'trait-'+t.toLowerCase()).join(' ')} ${selectedBattle===x.id?'selected-unit':''}" style="left:${x.progress}%;--lane:${(i%4)*3}px" data-action="inspect:enemy:${x.id}" aria-label="Inspect ${x.kind}"><em class="unit-hp" style="--hp:${Math.max(0,x.hp/x.maxHp*100)}%"></em>${traits.length?`<b class="trait-badge">${traits[0]}</b>`:''}<span>${x.kind}</span></button>`}).join('')+battle.projectiles.map(p=>`<i class="projectile ${p.type}" style="left:${p.x}%"></i>`).join('')+battle.projectiles.filter(p=>selectedBattle===p.source||selectedBattle===p.target).map(p=>{const target=battle!.enemies.find(x=>x.id===p.target),end=target?.progress??p.x,left=Math.min(p.x,end),width=Math.abs(p.x-end);return `<i class="target-line" style="left:${left}%;width:${width}%"></i>`}).join('');
  }
  renderCombatEvents(battle.drainEvents());const set=(id:string,v:string)=>{const x=document.querySelector(id);if(x)x.textContent=v};set('#integrity',`${Math.ceil(battle.integrity)}%`);set('#threats',String(battle.enemies.length));set('#wave',battle.time<8?'1':battle.time<18?'2':'3');if(game!.settings.autoPause&&speed>0&&battle.heroes.some(h=>h.downed&&!h.history.at(-1)?.includes('acknowledged'))){speed=0;for(const h of battle.heroes.filter(h=>h.downed))h.history.push('Commander acknowledged the injury.');}if(battle.status!=='running'){finish();return;}raf=requestAnimationFrame(loop);
}
function renderCombatEvents(events:ReturnType<Battle['drainEvents']>){const fx=document.querySelector('#combat-effects'),alerts=document.querySelector('#battle-alerts');for(const ev of events){const target=battle?.enemies.find(e=>e.id===ev.target),hero=battle?.heroes.find(h=>h.id===ev.target),x=target?.progress??(hero?stationX[hero.station]:90);if((ev.type==='damage'||ev.type==='weakness')&&fx){const n=document.createElement('i'),hit=document.createElement('i');n.className=`damage-number ${ev.type}`;n.style.left=`${x}%`;n.textContent=ev.type==='weakness'?`${ev.label} ${ev.value}`:`-${ev.value}`;hit.className='impact hurt';hit.style.left=`${x}%`;fx.append(n,hit);setTimeout(()=>{n.remove();hit.remove()},850);}if(ev.type==='death'&&fx){const d=document.createElement('i');d.className='impact death';d.style.left=`${x}%`;fx.append(d);setTimeout(()=>d.remove(),700);}if((ev.type==='downed'||ev.type==='breach')&&alerts){const a=document.createElement('div');a.className=`battle-alert ${ev.type}`;a.textContent=ev.label||ev.type.toUpperCase();alerts.append(a);setTimeout(()=>a.remove(),2200);}}
}
function finish(){if(!battle)return;const won=battle.status==='victory';game!.integrity=Math.ceil(battle.integrity);for(const e of battle.enemies)game!.bestiary[e.kind]=(game!.bestiary[e.kind]||0)+1;if(won&&battle.reward)applyVictory(game!,battle.reward);else{game!.day++;game!.gold=Math.max(0,game!.gold-20);game!.history.push(`Night ${game!.night} — The defense broke. Repairs cost 20 gold.`);game!.integrity=100;}saveGame(game!);won?audio.victory():audio.defeat();const reward=battle.reward,downed=game!.heroes.filter(h=>h.injury);app.innerHTML=`<section class="result ${won?'victory':'defeat'}"><p class="eyebrow">Night concluded</p><h1>${won?'VICTORY':'GRAVENHOLD ENDURES'}</h1><p>${won?`Gravenhold survived. +${reward?.xp} XP · +${reward?.jp} JP · +${reward?.gold} gold`:'The Keep was breached, but no save is lost.'}</p>${downed.length?`<p>Injured: ${downed.map(h=>h.name).join(', ')}</p>`:''}${reward?.items.length?`<p>Loot: ${reward.items.join(', ')}</p>`:''}${button('RETURN TO DAY','return')}</section>`;battle=null;}
function go(screen:string){if(!game)return title();({ 'War Room':war,Barracks:barracks,Armory:armory,Training:training,Jobs:jobs,Infirmary:infirmary,Bestiary:bestiary,Chronicle:chronicle,Settings:settings }[screen]||war)();}
app.addEventListener('change',e=>{const t=e.target as HTMLInputElement;if(t.dataset.hero&&game){game.heroes.find(h=>h.id===t.dataset.hero)!.station=t.value as Station;saveGame(game);}else if(t.dataset.setting&&game){const key=t.dataset.setting as keyof SaveGame['settings'];(game.settings as any)[key]=t.type==='checkbox'?t.checked:Number(t.value);audio.enabled=game.settings.master>0;document.documentElement.classList.toggle('reduced-motion',game.settings.reducedMotion);saveGame(game);}});
app.addEventListener('click',e=>{const el=(e.target as HTMLElement).closest<HTMLElement>('[data-action]');if(!el)return;audio.click();const [a,b,c]=el.dataset.action!.split(':');if(a==='new'){game=newGame();saveGame(game);war();}else if(a==='continue'){game=loadGame();go('War Room');}else if(a==='screen')go(b);else if(a==='title'){cancelAnimationFrame(raf);title();}else if(a==='save'){saveGame(game!,b);el.textContent='SAVED';}else if(a==='hero'){selected=b;barracks();}else if(a==='learn'){const h=game!.heroes.find(x=>x.id===b)!;learn(h,c);saveGame(game!);training();}else if(a==='promote'){const h=game!.heroes.find(x=>x.id===b)!,node=jobTree.find(n=>n.name===c)!;promote(h,node);saveGame(game!);jobs();}else if(a==='equip'){const item=itemByName(game!.inventory.find(n=>itemByName(n)?.id===b)||'');const select=el.parentElement?.querySelector<HTMLSelectElement>(`select[data-equip="${b}"]`),h=game!.heroes.find(x=>x.id===select?.value);if(item&&h)equipItem(h,item);saveGame(game!);armory();}else if(a==='build'){const costs:{[k:string]:number}={Ballista:80,'Holy Ward':70};game!.gold-=costs[b];game!.defenses.push(b==='Ballista'?{id:'ballista',kind:'Ballista',position:60,range:42,cooldown:3,nextAttack:0,damage:58,type:'physical'}:{id:'ward',kind:'Holy Ward',position:79,range:13,cooldown:2.5,nextAttack:0,damage:32,type:'holy'});saveGame(game!);war();}else if(a==='begin'){saveGame(game!);repairCharge=flareCharge=1;night();}else if(a==='speed')speed=Number(b);else if(a==='repair'&&battle&&repairCharge){battle.emergencyRepair(game!.heroes.find(h=>h.job==='Engineer')?.learned.includes('Field Repair')?25:15);repairCharge=0;el.setAttribute('disabled','');}else if(a==='flare'&&battle&&flareCharge){battle.holyFlare();flareCharge=0;el.setAttribute('disabled','');}else if(a==='rally'&&battle){for(const h of battle.heroes)h.nextAttack=Math.min(h.nextAttack,battle.time);el.setAttribute('disabled','');}else if(a==='return')war();});
app.addEventListener('click',e=>{const el=(e.target as HTMLElement).closest<HTMLElement>('[data-action]');if(!el)return;const [a,b,c]=el.dataset.action!.split(':');if(a==='new')setTimeout(()=>showTutorial(0));else if(a==='tutorial')showTutorial(0);else if(a==='tutorial-close')closeTutorial();else if(a==='tutorial-back')showTutorial(tutorialIndex-1);else if(a==='tutorial-next'){if(tutorialIndex===tutorialSteps.length-1){if(game){game.settings.tutorialComplete=true;saveGame(game);}closeTutorial();}else showTutorial(tutorialIndex+1);}else if(a==='inspect'&&battle){selectedBattle=c;const panel=document.querySelector('#battle-inspector');if(!panel)return;if(b==='hero'){const h=battle.heroes.find(x=>x.id===c);if(h)panel.innerHTML=`<b>${h.name} · ${h.job}</b><span>${h.station} · HP ${Math.ceil(h.hp)}/${h.maxHp} · ATK ${h.attack} · ARM ${h.armor} · RNG ${h.range}</span>`;}else{const enemy=battle.enemies.find(x=>x.id===c);if(enemy)panel.innerHTML=`<b>${enemy.kind}</b><span>HP ${Math.ceil(enemy.hp)}/${enemy.maxHp} · ARM ${enemy.armor} · ${enemy.weak?`Weak: ${enemy.weak.toUpperCase()}`:'No known weakness'} · ${enemyTraits(enemy.kind,enemy.flying).join(' / ')||'GROUND'}</span>`;}}});
document.addEventListener('click',e=>{const el=(e.target as HTMLElement).closest<HTMLElement>('#tutorial-overlay [data-action]');if(!el)return;const a=el.dataset.action;if(a==='tutorial-close')closeTutorial();else if(a==='tutorial-back')showTutorial(tutorialIndex-1);else if(a==='tutorial-next'){if(tutorialIndex===tutorialSteps.length-1){if(game){game.settings.tutorialComplete=true;saveGame(game);}closeTutorial();}else showTutorial(tutorialIndex+1);}});
title();
